- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: LH
    with_frame: true
    name: pcg_door_LH_from_primitives_with_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: RH
    with_frame: true
    name: pcg_door_RH_from_primitives_with_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: LHR
    with_frame: true
    name: pcg_door_LHR_from_primitives_with_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: RHR
    with_frame: true
    name: pcg_door_RHR_from_primitives_with_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: LH
    with_frame: false
    name: pcg_door_LH_from_primitives_no_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: RH
    with_frame: false
    name: pcg_door_RH_from_primitives_no_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: LHR
    with_frame: false
    name: pcg_door_LHR_from_primitives_no_frame
- type: hinged_door
  args:
    width: 0.65
    thickness: 0.04
    height: 2.0
    mass: 10
    hand_convention: RHR
    with_frame: false
    name: pcg_door_RHR_from_primitives_no_frame