sudo: required
dist: trusty
language: generic
compiler:
  - gcc
cache:
  directories:
    - $HOME/.ccache  # can be any valid cache location
env:
  global:
    - LIBGL_ALWAYS_SOFTWARE=1
    - VERBOSE_OUTPUT='false'
    - CATKIN_CONFIG='--no-install'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
    - CCACHE_DIR=$HOME/.ccache
    - CATKIN_LINT=true
    - CATKIN_LINT_ARGS="--ignore link_directory"
    - UPSTREAM_WORKSPACE=true
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=false
    - NOT_TEST_INSTALL=true
matrix:
  include:
    # - env: BEFORE_SCRIPT="apt update && apt install libspatialindex-dev && pip install pip --upgrade" ROS_DISTRO=melodic 
    # - env: BEFORE_SCRIPT="apt update && apt install software-properties-common && pip install pip --upgrade && add-apt-repository ppa:thomas-schiex/blender -y && apt update && apt install blender libspatialindex-dev -y" ROS_DISTRO=kinetic
    - env: BEFORE_SCRIPT="apt update && apt install libfcl-dev && pip install pip --upgrade" ROS_DISTRO=melodic 
    - env: BEFORE_SCRIPT="apt update && apt install software-properties-common && pip install pip --upgrade && add-apt-repository ppa:thomas-schiex/blender -y && apt update && apt install blender -y" ROS_DISTRO=kinetic
  allow_failures:
    - env: BEFORE_SCRIPT="apt update && apt install software-properties-common && pip install pip --upgrade && add-apt-repository ppa:thomas-schiex/blender -y && apt update && apt install blender -y" ROS_DISTRO=kinetic
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - source .ci_config/travis.sh