sudo: required
dist: trusty
language: generic
compiler:
  - gcc
cache:
  directories:
    - $HOME/.ccache  # can be any valid cache location
env:
  global:
    - LIBGL_ALWAYS_SOFTWARE=1
    - VERBOSE_OUTPUT='false'
    - CATKIN_CONFIG='--no-install'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
    - CCACHE_DIR=$HOME/.ccache
    - CATKIN_LINT=true
    - CATKIN_LINT_ARGS="--ignore link_directory"
    - UPSTREAM_WORKSPACE=true
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=false
    - NOT_TEST_INSTALL=true
    - BEFORE_SCRIPT="pip install pip --upgrade && add-apt-repository ppa:openscad/releases -y && apt install openscad -y"
matrix:
  include:
    - env: ROS_DISTRO=melodic 
    - env: ROS_DISTRO=kinetic

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - source .ci_config/travis.sh