engine: bullet
args:
  max_step_size: 0.001
  real_time_factor: 1
  real_time_update_rate: 1000
  max_contacts: 20
  min_step_size: 0.001
  iters: 50
  sor: 1.3
  cfm: 0
  erp: 0.2
  contact_surface_layer: 0.001
  split_impulse: True
  split_impulse_penetration_threshold: -0.01