engine: ode
args:
  max_step_size: 0.001
  real_time_factor: 1
  real_time_update_rate: 1000
  max_contacts: 20
  min_step_size: 0.0001
  iters: 50
  sor: 1.3
  type: quick
  precon_iters: 0
  use_dynamic_moi_rescaling: false
  friction_model: pyramid_model
  cfm: 0
  erp: 0.2
  contact_surface_layer: 0.001
  contact_max_correcting_vel: 100