name: empty_world_bullet
engines: 
- engine_name: fixed_pose
  models:
  - ground_plane
  poses:
  - [0, 0, 0, 0, 0, 0]
- engine_name: fixed_pose
  models:
  - sun
  poses:
  - [0, 0, 10, 0, 0, 0]
physics: !find pcg_examples/config/world_generator/physics/default_bullet.yml