- type: sphere_factory
  args:
    radius: "__import__('numpy').linspace(0.1, 10, 3)"    
    use_permutation: true
    name: sphere_static_lambdas
    color: xkcd
- type: sphere_factory
  args:
    radius: "__import__('numpy').random.random(2)"
    mass: "__import__('numpy').arange(1, 4, 1)"
    use_permutation: true
    name: sphere_dynamic_lambdas
    color: xkcd